# @base_url = http://localhost:8000/tasks
@base_url = https://react-native-task.herokuapp.com/tasks

# Obtener todas las tareas
GET {{base_url}}

# Obtener una tarea segun el id
###
GET {{base_url}}/1

# Obtener la cantidad de tareas
###
GET {{base_url}}/count

# Crear una tarea
###
POST {{base_url}}
Content-Type: application/json 

{
    "title": "EJEMPLO3",
    "description": "EJEMPLOSSS3"
}

# Eliminar una tarea por id
###
DELETE {{base_url}}/14

# actualiza una tarea
###
PUT {{base_url}}/11
Content-Type: application/json 

{
    "title": "React native",
    "description": "Aprender react native lo mas rapido"
}